/**
 * Resolves folder/file names to icon SVG data from mapping rules.
 * Data generated by: node scripts/fetch-workspace-icons.mjs
 */
// eslint-disable-next-line @typescript-eslint/no-require-imports
const ICON_DATA = require("../../assets/icons/workspace-icon-svgs.json") as {
  svgData: Record<string, string>;
  folderNameToId: Record<string, string>;
  fileExtToId: Record<string, string>;
  fileNameToId: Record<string, string>;
  defaultFolderId: string | null;
  defaultFolderOpenId: string | null;
  defaultFileId: string | null;
};

export function getFolderIconSvg(
  folderName: string,
  expanded: boolean
): string | null {
  const key = folderName.toLowerCase();
  const iconId =
    ICON_DATA.folderNameToId[key] ??
    (expanded ? ICON_DATA.defaultFolderOpenId : ICON_DATA.defaultFolderId);
  return iconId ? ICON_DATA.svgData[iconId] ?? null : null;
}

export function getFileIconSvg(fileName: string): string | null {
  const nameLower = fileName.toLowerCase();
  let iconId = ICON_DATA.fileNameToId[nameLower];
  if (!iconId) {
    const ext = nameLower.includes(".")
      ? nameLower.split(".").pop() ?? ""
      : "";
    iconId = ICON_DATA.fileExtToId[ext] ?? ICON_DATA.defaultFileId;
  }
  return iconId ? ICON_DATA.svgData[iconId] ?? null : null;
}
